# a minimal environment for building the book from source
#  assuming all notebooks are already up-to-date
name: book-render
channels:
  - conda-forge
dependencies:
  - jupyter-book  # needed to rebuild the book from source
  - numpy
  - scipy
  - matplotlib
  - rebound
